import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./styles/globals.css";
import { Header, Footer } from "@/components/GlobalComponents";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-radial-[at_25%_25%] from-[#C8DCE5] to-[#B6CCDA]`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
